import type { PolicyDocument } from './types'

export const termsPolicy: PolicyDocument = {
  slug: "terms",
  title: "Terms & Conditions",
  description: "Terms governing access to CrossResearch services, research, and analytical tools.",
  intro: [
  "These Terms & Conditions (\"Terms\") govern your access to and use of the CrossResearch website, applications, platform, subscriptions, research, market intelligence, indicators, analytical tools, artificial-intelligence features, alerts, publications, data and related services (collectively, the \"Services\").",
  "By creating an account, purchasing a subscription, accessing paid Services, or otherwise using the Services, you agree to these Terms and our Privacy Policy.",
  "If you do not agree, you must not use the Services."
  ],
  contactEmail: "admin@crossresearch.io",
  sections: [
    {
      id: "research-provider",
      title: "CrossResearch Is a Research and Technology Provider",
      number: 1,
      blocks: [
      { type: 'p', text: "CrossResearch provides financial information, independent market research, educational content, analytical technology and software tools." },
      { type: 'p', text: "CrossResearch is not a broker, dealer, investment manager, portfolio manager, investment adviser, financial adviser, fiduciary, custodian, exchange or trade-execution service." },
      { type: 'p', text: "CrossResearch does not execute or arrange transactions, receive or control customer funds, manage portfolios, determine the suitability of investments, exercise discretionary authority over user assets, or make investment decisions on behalf of users." },
      { type: 'p', text: "Use of CrossResearch does not create an adviser-client, broker-client, fiduciary, agency, partnership or similar professional relationship." },
      ],
    },
    {
      id: "information-only",
      title: "Information and Education Only",
      number: 2,
      blocks: [
      { type: 'p', text: "All content and outputs made available through CrossResearch are provided solely for informational, analytical, research and educational purposes." },
      { type: 'p', text: "This includes research, commentary, news analysis, forecasts, probabilities, scenarios, indicators, signals, ratings, market views, technical analysis, macroeconomic analysis, quantitative analysis, screeners, charts, dashboards, models, alerts, backtests, simulations, AI-generated outputs and educational material." },
      { type: 'p', text: "Nothing provided through CrossResearch constitutes or should be interpreted as personalized investment advice, financial advice, legal advice, tax advice, an offer, solicitation, instruction or recommendation to buy, sell, hold or otherwise transact in any security, derivative, cryptocurrency, commodity, currency or other financial instrument." },
      { type: 'p', text: "The fact that CrossResearch discusses a particular asset, identifies an opportunity or risk, assigns a bullish or bearish view, estimates a probability, generates an alert or signal, or responds to a user's question does not convert that information into personalized investment advice." },
      ],
    },
    {
      id: "user-decisions",
      title: "The User Makes All Investment Decisions",
      number: 3,
      blocks: [
      { type: 'p', text: "Every investment, trading and financial decision remains solely and independently the responsibility of the user." },
      { type: 'p', text: "CrossResearch does not assess a user's complete financial circumstances, investment objectives, experience, portfolio, liquidity requirements, tax position, risk tolerance or suitability requirements." },
      { type: 'p', text: "Users are responsible for independently evaluating all information, conducting their own research, verifying relevant data, establishing their own risk limits and determining whether, when and how to enter, hold, size, hedge or exit any position." },
      { type: 'p', text: "CrossResearch content should not be used as the sole basis for an investment or trading decision." },
      { type: 'p', text: "If a user decides to trade, invest or otherwise act after reviewing information provided by CrossResearch, that decision is made independently by the user and at the user's own risk." },
      ],
    },
    {
      id: "investment-risk",
      title: "Investment and Trading Risk",
      number: 4,
      blocks: [
      { type: 'p', text: "Trading and investing involve substantial risk and may result in the loss of some or all capital." },
      { type: 'p', text: "Leveraged products, derivatives, cryptocurrencies and other volatile instruments may involve particularly significant risk and may, depending on the instrument and jurisdiction, result in losses exceeding the amount initially committed." },
      { type: 'p', text: "Past performance is not necessarily indicative of future results." },
      { type: 'p', text: "CrossResearch makes no representation, promise or guarantee that any user, strategy, signal, model or analysis will generate profits, prevent losses or achieve any particular result." },
      { type: 'p', text: "Users should obtain independent professional advice where appropriate." },
      ],
    },
    {
      id: "ai-algorithms",
      title: "AI, Algorithms and Analytical Models",
      number: 5,
      blocks: [
      { type: 'p', text: "CrossResearch may use artificial intelligence, statistical models, quantitative models, algorithms and other automated systems to produce or assist with analysis." },
      { type: 'p', text: "Such systems can produce inaccurate, incomplete, outdated, inconsistent or misleading results and may fail to identify relevant information or risks." },
      { type: 'p', text: "AI and model-generated outputs are analytical tools." },
      { type: 'p', text: "They are not autonomous financial decision-makers and do not constitute personalized advice." },
      { type: 'p', text: "Where users provide prompts, filters, preferences, instruments, parameters, strategies, assumptions or other inputs, those inputs remain selected by the user." },
      { type: 'p', text: "A CrossResearch system responding to user-defined inputs does not constitute a determination by CrossResearch that an investment or strategy is suitable or appropriate." },
      { type: 'p', text: "Users must independently review and validate material outputs before acting upon them." },
      { type: 'p', text: "CrossResearch does not guarantee the accuracy, completeness, originality, reliability or suitability of AI-generated or model-generated output." },
      ],
    },
    {
      id: "backtests",
      title: "Backtests, Simulations and Hypothetical Performance",
      number: 6,
      blocks: [
      { type: 'p', text: "Backtests, simulations, hypothetical portfolios, strategy examples and historical performance illustrations do not represent actual trading unless expressly stated otherwise." },
      { type: 'p', text: "Hypothetical results may benefit from hindsight and may not adequately reflect real-world factors including liquidity, spreads, commissions, slippage, latency, market impact, rejected orders, execution quality, changing market regimes, transaction costs, data limitations, survivorship bias, look-ahead bias and financial or psychological pressures experienced during live trading." },
      { type: 'p', text: "Actual results may differ materially from simulated or hypothetical results." },
      { type: 'p', text: "No representation is made that any account or strategy will achieve results comparable to those displayed." },
      ],
    },
    {
      id: "research-opinions",
      title: "Research Opinions, Forecasts and Updates",
      number: 7,
      blocks: [
      { type: 'p', text: "Research, opinions, forecasts, probabilities, ratings, signals and analytical conclusions reflect information, assumptions and views available at the time they are produced." },
      { type: 'p', text: "They may change at any time as market conditions, data, assumptions or circumstances change." },
      { type: 'p', text: "CrossResearch is under no obligation to update, amend or withdraw previously published research merely because subsequent information, market movements or events cause an earlier view to become outdated, inaccurate or unsuccessful." },
      { type: 'p', text: "Where content identifies an individual author, analyst, contributor, strategist or third-party source, statements of opinion represent that person's analytical view and do not constitute a guarantee or promise by CrossResearch regarding future performance." },
      ],
    },
    {
      id: "market-data",
      title: "Market Data Is Not an Execution Source",
      number: 8,
      blocks: [
      { type: 'p', text: "Market data, prices, quotes, yields, spreads, economic information, calculations and other information displayed through CrossResearch may originate from CrossResearch, public sources or third-party providers." },
      { type: 'p', text: "Information may be delayed, estimated, incomplete, unavailable or inaccurate." },
      { type: 'p', text: "Different exchanges, brokers, vendors and platforms may display different information because of differences in data sources, timestamps, methodology, rounding, corporate-action treatment, instrument specifications or other factors." },
      { type: 'p', text: "CrossResearch is not an exchange, broker, execution venue or official source of executable market prices." },
      { type: 'p', text: "Information displayed through CrossResearch must not be treated as a guaranteed executable quotation, settlement value, order-verification price or official valuation." },
      { type: 'p', text: "Users should verify relevant information with an appropriate broker, exchange, execution venue or primary source before entering into a transaction." },
      ],
    },
    {
      id: "alerts-signals",
      title: "Alerts, Signals and Communications",
      number: 9,
      blocks: [
      { type: 'p', text: "CrossResearch may provide alerts, notifications, emails, messages, signals, API responses or similar communications." },
      { type: 'p', text: "Delivery is not guaranteed." },
      { type: 'p', text: "Alerts or communications may be delayed, duplicated, interrupted, unavailable or fail entirely due to internet connectivity, software errors, third-party infrastructure, provider outages, rate limits, market conditions or other circumstances." },
      { type: 'p', text: "Alerts and signals constitute informational outputs only and are not instructions to execute transactions." },
      { type: 'p', text: "CrossResearch does not monitor whether users have acted upon an alert and assumes no responsibility for transactions entered, omitted, delayed or modified because of an alert, signal or communication." },
      ],
    },
    {
      id: "third-party",
      title: "Third-Party Services, Data and Affiliates",
      number: 10,
      blocks: [
      { type: 'p', text: "CrossResearch may integrate with or reference third-party websites, software, platforms, APIs, data providers, payment processors, AI providers, brokers, exchanges, publishers and other services." },
      { type: 'p', text: "Those services remain independent third parties and may be subject to their own terms, licences and privacy policies." },
      { type: 'p', text: "CrossResearch does not control and is not responsible for their availability, accuracy, security, conduct, content or performance." },
      { type: 'p', text: "Certain data, news, trademarks, indices, reference information or other content made available through CrossResearch may be owned or licensed by third parties." },
      { type: 'p', text: "Access through CrossResearch does not transfer ownership or grant users unrestricted redistribution or commercial-use rights in such materials." },
      { type: 'p', text: "Users must comply with applicable third-party licensing restrictions." },
      { type: 'p', text: "CrossResearch may restrict, modify or discontinue access to particular data or functionality where required by a licensor, provider, law or contractual obligation." },
      { type: 'p', text: "CrossResearch may participate in affiliate, referral or commercial partnerships and may receive compensation when users interact with or purchase products or services from certain third parties." },
      { type: 'p', text: "Such compensation does not transform CrossResearch into a broker, adviser or fiduciary and does not constitute a recommendation that a third-party product is suitable for a particular user." },
      ],
    },
    {
      id: "intellectual-property",
      title: "Intellectual Property",
      number: 11,
      blocks: [
      { type: 'p', text: "CrossResearch and its licensors retain all applicable rights, title and interest in the Services and their underlying intellectual property." },
      { type: 'p', text: "This includes, where applicable, the CrossResearch brand, name, trademarks, logos, research, publications, methodologies, models, scoring systems, indicators, signals, algorithms, software, code, prompts, system architecture, databases, compilations, dashboards, user-interface designs, charts, visualizations, graphics, educational material and other proprietary content or technology." },
      { type: 'p', text: "Purchasing or accessing CrossResearch grants only a limited, non-exclusive, non-transferable, non-sublicensable and revocable licence to use the Services within the scope of the user's applicable subscription or product licence." },
      { type: 'p', text: "No ownership rights are transferred to the user." },
      { type: 'p', text: "Unless CrossResearch expressly authorizes otherwise in writing, users may not reproduce, redistribute, republish, resell, sublicense, scrape, systematically extract, commercially exploit, reverse engineer, decompile, clone or create unauthorized derivative products from CrossResearch proprietary material." },
      { type: 'p', text: "Users may not:" },
      {
        type: 'ul',
        items: [
          "share or resell paid access or account credentials;",
          "reproduce or redistribute paid research;",
          "systematically download or extract CrossResearch databases or content;",
          "clone proprietary indicators, models, scoring systems or methodologies;",
          "remove copyright, trademark or proprietary notices;",
          "represent CrossResearch content as their own;",
          "circumvent subscription, security or access controls;",
          "use CrossResearch proprietary materials to create a competing product or substitute service; or",
          "use proprietary CrossResearch content to train, fine-tune, develop or populate third-party AI models, datasets or knowledge bases without written authorization."
        ],
      },
      { type: 'p', text: "Nothing in these Terms restricts uses that cannot lawfully be prohibited, including quotations or other uses permitted under applicable copyright law." },
      ],
    },
    {
      id: "copyright-enforcement",
      title: "Copyright and Intellectual-Property Enforcement",
      number: 12,
      blocks: [
      { type: 'p', text: "CrossResearch actively protects and enforces its intellectual-property and contractual rights." },
      { type: 'p', text: "Where CrossResearch reasonably suspects unauthorized copying, scraping, account sharing, redistribution, resale, reverse engineering, systematic extraction, infringement or other misuse, CrossResearch may investigate the activity and preserve relevant account, access and technical records as permitted by applicable law." },
      { type: 'p', text: "CrossResearch may suspend or terminate access, request removal of infringing content, issue takedown notices or cease-and-desist demands, notify relevant hosting providers, platforms or service providers and pursue available legal remedies." },
      { type: 'p', text: "To the extent permitted by applicable law, CrossResearch expressly reserves the right to seek injunctive or equitable relief, damages, recovery of profits attributable to infringement, reasonable legal costs and any other remedy available under law." },
      { type: 'p', text: "Termination of access does not prevent CrossResearch from pursuing claims relating to conduct occurring before termination." },
      { type: 'p', text: "Intellectual-property, confidentiality, data-use and enforcement obligations that by their nature should survive termination shall continue after access to the Services ends." },
      ],
    },
    {
      id: "user-inputs",
      title: "User Inputs and Content",
      number: 13,
      blocks: [
      { type: 'p', text: "Users may provide prompts, messages, settings, strategies, configurations, documents, feedback or other content to the Services." },
      { type: 'p', text: "Users remain responsible for the material they submit and represent that they possess the necessary rights and authority to use it." },
      { type: 'p', text: "Users must not knowingly submit material that unlawfully infringes another person's copyright, confidentiality, privacy, trademark, trade-secret or other rights." },
      { type: 'p', text: "CrossResearch may remove or restrict content that violates these Terms or applicable law." },
      { type: 'p', text: "Treatment of personal information contained in user content is governed by the Privacy Policy." },
      ],
    },
    {
      id: "accounts-security",
      title: "Accounts and Security",
      number: 14,
      blocks: [
      { type: 'p', text: "Users must be legally capable of entering into a binding contract and must be at least 18 years old unless CrossResearch expressly permits otherwise under applicable law." },
      { type: 'p', text: "Registration information must be accurate and current." },
      { type: 'p', text: "Users are responsible for protecting their credentials and for activity occurring through their account." },
      { type: 'p', text: "Unauthorized access or suspected credential compromise should be reported promptly." },
      { type: 'p', text: "Accounts may not be sold, transferred or shared outside the permissions of the relevant subscription." },
      ],
    },
    {
      id: "prohibited-uses",
      title: "Prohibited Uses",
      number: 15,
      blocks: [
      { type: 'p', text: "Users may not use the Services to violate applicable law, infringe third-party rights, distribute malware, interfere with platform security or operation, obtain unauthorized access, impersonate others, manipulate the Services, abuse technical infrastructure, evade payment or subscription restrictions, conduct unauthorized scraping or extraction, or facilitate activity expressly prohibited by these Terms." },
      { type: 'p', text: "CrossResearch may implement reasonable technical measures to detect and prevent abuse." },
      ],
    },
    {
      id: "subscriptions",
      title: "Subscriptions, Payments and Cancellation",
      number: 16,
      blocks: [
      { type: 'p', text: "Certain Services require payment." },
      { type: 'p', text: "Applicable prices, billing periods, renewal conditions and taxes will be presented at or before purchase." },
      { type: 'p', text: "Where a subscription is recurring, it will renew according to the billing terms presented to the user unless cancelled before the applicable renewal." },
      { type: 'p', text: "Cancellation prevents future renewal but generally does not terminate access already paid for during the current billing period unless otherwise stated." },
      { type: 'p', text: "Except where CrossResearch expressly offers a refund or applicable law requires otherwise, payments for periods already supplied are non-refundable." },
      { type: 'p', text: "Nothing in these Terms limits statutory withdrawal, cancellation, refund or other consumer rights that cannot legally be excluded." },
      { type: 'p', text: "Where applicable law permits a consumer to request immediate performance of digital content or digital services during a statutory withdrawal period, any resulting effect on withdrawal rights will apply only where the legally required information, consent and acknowledgement have been obtained." },
      { type: 'p', text: "Payment processing may be performed by third parties and may additionally be subject to their terms." },
      { type: 'p', text: "CrossResearch may suspend access associated with payments that are reversed, fraudulently disputed or otherwise invalid, subject to applicable law." },
      ],
    },
    {
      id: "service-availability",
      title: "Service Availability and Changes",
      number: 17,
      blocks: [
      { type: 'p', text: "CrossResearch may modify, improve, replace, suspend or discontinue features as its Services develop." },
      { type: 'p', text: "CrossResearch aims to provide reliable Services but cannot guarantee uninterrupted operation." },
      { type: 'p', text: "Availability may be affected by maintenance, market-data outages, internet failures, third-party providers, cybersecurity incidents, software defects, APIs, infrastructure failures or circumstances outside CrossResearch's reasonable control." },
      { type: 'p', text: "CrossResearch does not guarantee backward compatibility of all features, integrations, indicators, APIs or analytical outputs." },
      ],
    },
    {
      id: "disclaimer-warranties",
      title: "Disclaimer of Warranties",
      number: 18,
      blocks: [
      { type: 'p', text: "To the fullest extent permitted by applicable law, the Services and all associated information are provided \"as is\" and \"as available.\" CrossResearch makes no guarantee or warranty that information or Services will be uninterrupted, error-free, accurate, complete, current, secure, profitable, suitable for a particular purpose or compatible with any particular trading methodology, platform or investment objective." },
      { type: 'p', text: "No statement made by CrossResearch should be interpreted as a guarantee of investment performance." },
      ],
    },
    {
      id: "limitation-liability",
      title: "Limitation of Liability",
      number: 19,
      blocks: [
      { type: 'p', text: "To the fullest extent permitted by applicable law, CrossResearch and its owners, directors, officers, employees, affiliates, contractors, licensors and service providers shall not be liable for trading or investment losses, loss of capital, loss of profits, loss of opportunity, lost data, business interruption, inaccurate or delayed data, AI or model errors, alert failures, third-party failures or indirect, incidental, special, exemplary or consequential damages arising from or connected with the Services." },
      { type: 'p', text: "Where liability cannot lawfully be excluded entirely, CrossResearch's aggregate liability arising from the Services shall, to the fullest extent permitted by law, not exceed the amount actually paid by the affected user to CrossResearch during the twelve months preceding the event giving rise to the claim." },
      { type: 'p', text: "Nothing in these Terms excludes or limits liability where exclusion or limitation is prohibited by applicable law." },
      ],
    },
    {
      id: "indemnification",
      title: "Indemnification",
      number: 20,
      blocks: [
      { type: 'p', text: "To the extent permitted by applicable law, users are responsible for losses, liabilities, claims and reasonable enforcement costs caused by their unlawful misuse of the Services, violation of these Terms, infringement of intellectual-property rights, unauthorized redistribution of content, or violation of applicable law or third-party rights." },
      ],
    },
    {
      id: "suspension-termination",
      title: "Suspension and Termination",
      number: 21,
      blocks: [
      { type: 'p', text: "CrossResearch may reasonably restrict, suspend or terminate access because of breach of these Terms, fraud, payment abuse, unauthorized account sharing, intellectual-property infringement, unlawful activity, cybersecurity threats, misuse of the Services or attempts to compromise the platform." },
      { type: 'p', text: "Where circumstances reasonably require immediate action to protect CrossResearch, its users, licensors, systems or rights, suspension may occur without prior notice." },
      { type: 'p', text: "Termination does not affect rights or obligations arising before termination." },
      ],
    },
    {
      id: "privacy",
      title: "Privacy",
      number: 22,
      blocks: [
      { type: 'p', text: "Processing of personal data in connection with the Services is governed by the CrossResearch Privacy Policy." },
      ],
    },
    {
      id: "changes-terms",
      title: "Changes to These Terms",
      number: 23,
      blocks: [
      { type: 'p', text: "CrossResearch may update these Terms to reflect changes in the Services, business operations, law, regulation, security requirements or contractual obligations." },
      { type: 'p', text: "Where required by applicable law, users will receive advance notice of material changes affecting an existing subscription or their rights." },
      { type: 'p', text: "The current version and effective date will remain available through the CrossResearch website." },
      ],
    },
    {
      id: "consumer-rights",
      title: "Mandatory Consumer Rights",
      number: 24,
      blocks: [
      { type: 'p', text: "Nothing in these Terms is intended to remove or restrict consumer rights that cannot legally be waived." },
      { type: 'p', text: "Where mandatory applicable law conflicts with a provision of these Terms, that mandatory law shall prevail only to the extent of the conflict." },
      ],
    },
    {
      id: "governing-law",
      title: "Governing Law and Jurisdiction",
      number: 25,
      blocks: [
      { type: 'p', text: "These Terms and any dispute arising from them shall be governed by the laws of:" },
      { type: 'p', text: "Lithuania" },
      { type: 'p', text: "Subject to mandatory rights available under applicable consumer law, the competent courts shall be:" },
      { type: 'p', text: "Lithuania" },
      { type: 'p', text: "Nothing in this section deprives a consumer of mandatory protections or jurisdictional rights that applicable law requires to remain available." },
      ],
    },
    {
      id: "severability",
      title: "Severability and Entire Agreement",
      number: 26,
      blocks: [
      { type: 'p', text: "If any provision is held invalid or unenforceable, it shall be limited or removed only to the minimum extent necessary, and the remaining Terms shall continue in effect." },
      { type: 'p', text: "These Terms, the Privacy Policy and any additional product or subscription terms expressly incorporated by reference constitute the agreement governing use of CrossResearch." },
      { type: 'p', text: "Failure by CrossResearch to enforce a provision on one occasion does not constitute a permanent waiver of that provision." },
      ],
    },
    {
      id: "contact",
      title: "Contact and Legal Entity",
      number: 27,
      blocks: [
      { type: 'p', text: "The Services are provided by:" },
      { type: 'p', text: "Crossresearch.io" },
      { type: 'p', text: "Legal enquiries:" },
      { type: 'p', text: "admin@crossresearch.io" },
      { type: 'p', text: "By using CrossResearch, the user acknowledges that CrossResearch provides information, research, education and analytical technology not personalized investment decisions and that every financial decision remains solely the responsibility of the user." },
      ],
    }
  ],
}
